//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delta_Utilities_Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Delta_Utilities_Activities.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Settings.
        /// </summary>
        public static string CreateSecureConnectionString_AdditionalSettings_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_AdditionalSettings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra connection parameters (e.g., TrustServerCertificate=True)..
        /// </summary>
        public static string CreateSecureConnectionString_AdditionalSettings_Tooltip {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_AdditionalSettings_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Catalog / DB Name.
        /// </summary>
        public static string CreateSecureConnectionString_DatabaseName_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_DatabaseName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the database or initial catalog to connect to..
        /// </summary>
        public static string CreateSecureConnectionString_DatabaseName_Tooltip {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_DatabaseName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Type.
        /// </summary>
        public static string CreateSecureConnectionString_DBType_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_DBType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of database (e.g., SQL Server, Oracle, ODBC)..
        /// </summary>
        public static string CreateSecureConnectionString_DBType_Tooltip {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_DBType_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a database connection string as a SecureString for enhanced security..
        /// </summary>
        public static string CreateSecureConnectionString_Description {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Secure Connection String.
        /// </summary>
        public static string CreateSecureConnectionString_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (Secure).
        /// </summary>
        public static string CreateSecureConnectionString_Password_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the connection provided as a SecureString..
        /// </summary>
        public static string CreateSecureConnectionString_Password_Tooltip {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_Password_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Connection String.
        /// </summary>
        public static string CreateSecureConnectionString_SecureConnectionString_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_SecureConnectionString_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resulting full connection string as a SecureString..
        /// </summary>
        public static string CreateSecureConnectionString_SecureConnectionString_Tooltip {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_SecureConnectionString_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server / Data Source.
        /// </summary>
        public static string CreateSecureConnectionString_Server_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_Server_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the server address or Data Source name..
        /// </summary>
        public static string CreateSecureConnectionString_Server_Tooltip {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_Server_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string CreateSecureConnectionString_Username_DisplayName {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_Username_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID used for the database connection..
        /// </summary>
        public static string CreateSecureConnectionString_Username_Tooltip {
            get {
                return ResourceManager.GetString("CreateSecureConnectionString_Username_Tooltip", resourceCulture);
            }
        }
    }
}
